name: Azure Function Web Api


on:
  workflow_call:
    inputs:
      Project:
        required: true
        type: string
        description: "Nome do Projeto que está sendo publicado"
      AppEnv:
        required: true
        type: string
        description: "Ambiente que será feito a publicação (DEV, HMG, STG, PRD, etc)"
      RootPath:
        required: true
        type: string
        description: "Pasta Raiz do projeto de Function (o caminho pode ser um path relativo do repositório, i.e., src/AzureFunction/)"
      OutPath:
        required: true
        type: string
        description: "Pasta de saída (local onde os binários são gerados. Pode ser um caminho relativo)"
      DotNetVersion:
        required: false
        type: string
        default: "10.0.x"
        description: "Versão do .net para fazer o build ('8.0.x' ou '10.0.x')"
      Configuration:
        required: false
        type: string
        default: "Release"
        description: "Configuração do build ('Debug' ou 'Release')"
      FunctionSlot:
        required: false
        type: string
        default: "Production"
        description: "Slot de publicação na Azure Function ('Production')"
      FunctionSku:
        required: false
        type: string
        default: "flexconsumption"
        description: "SKU de criação na Azure Function ('flexconsumption')"
    secrets:
      AZURE_CREDENTIALS:
        required: true
        description: |
          Json contendo as credenciais do Azure. para obter essa credencial, rode no azure o comando abaixo:
          az ad sp create-for-rbac --name "github-actions" --role contributor --scopes /subscriptions/#subscriptionId#
          O Azure vai retornar um Json semelhante ao abaixo
          {
            "appId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeffffff",
            "displayName": "github-actions",
            "password": "#Password+Secreta*Gerada+Automaticamente!",
            "tenant": "ffffffff-eeee-dddd-cccc-bbbbbbaaaaaa"
          }
          Você precisa converter o Json retornado acima em algo conforme o json abaixo:
          {
            "clientId": "appId",
            "clientSecret": "password",
            "subscriptionId": "#subscriptionId#",
            "tenantId": "tenant"
          }


jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    env:
      RESOURCE_NAME: "${{ inputs.Project }}-${{ inputs.AppEnv }}"
    
    steps:
      - name: Checkout GitHub Action v6
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup .NET Core ${{ inputs.DotNetVersion }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.DotNetVersion }}

      - name: Restore ${{ inputs.RootPath }}
        run: dotnet restore "${{ inputs.RootPath }}"

      - name: Build And Publish ${{ inputs.RootPath }} / ${{ inputs.Configuration }} in ${{ inputs.OutPath }}
        run: dotnet build "${{ inputs.RootPath }}" --configuration "${{ inputs.Configuration }}" --output "${{ inputs.OutPath }}"

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Function App ${{ inputs.Project }} @ ${{ inputs.AppEnv }} from ${{ inputs.OutPath }}
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.RESOURCE_NAME }}
          slot-name: ${{ inputs.FunctionSlot }}
          package: ${{ inputs.OutPath }}
          sku: ${{ inputs.FunctionSku }}
