name: Azure Static Web App


on:
  workflow_call:
    inputs:
      Project:
        required: true
        type: string
        description: "Nome do Projeto que está sendo publicado"
      AppEnv:
        required: true
        type: string
        description: "Ambiente que será feito a publicação (DEV, HMG, STG, PRD, etc)"
      AppType:
        required: true
        type: string
        description: "Indica o tipo de Static Web App (se é 'landing' page, ou 'webapp')"
      RootPath:
        required: true
        type: string
        description: "Pasta Raiz do projeto de Static Web App (o caminho pode ser um path relativo do repositório, i.e., src/BlazorApp/)"
      OutPath:
        required: true
        type: string
        description: "Pasta de saída do Static Web App (o caminho onde os binários são gerados. Pode ser um caminho relativo)"
      ApiUrl:
        required: true
        type: string
        description: "Endereço da Api (full url: https://api.servidor.com.br)"
      IncludeFileToReplace:
        required: true
        type: string
        description: "Indica os arquivos que serão submetidos para alterar o '#{BaseAddressUrl}'"
    secrets:
      AZURE_CREDENTIALS:
        required: true
        description: |
          Json contendo as credenciais do Azure. para obter essa credencial, rode no azure o comando abaixo:
          az ad sp create-for-rbac --name "github-actions" --role contributor --scopes /subscriptions/#subscriptionId#
          O Azure vai retornar um Json semelhante ao abaixo
          {
            "appId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeffffff",
            "displayName": "github-actions",
            "password": "#Password+Secreta*Gerada+Automaticamente!",
            "tenant": "ffffffff-eeee-dddd-cccc-bbbbbbaaaaaa"
          }
          Você precisa converter o Json retornado acima em algo conforme o json abaixo:
          {
            "clientId": "appId",
            "clientSecret": "password",
            "subscriptionId": "#subscriptionId#",
            "tenantId": "tenant"
          }


jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    env:
      ResourceGroup: "RG-${{ inputs.Project }}-${{ inputs.AppEnv }}"
      ResourceName: "${{ inputs.Project }}-${{ inputs.AppEnv }}${{ inputs.AppType }}"
      SufixAppName: ${{ inputs.AppEnv == "PRD" ? "" : inputs.AppEnv }}

    steps:
      - name: Checkout GitHub Action v6
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Find '#{BaseAddressUrl}' in '${{ inputs.RootPath }}/${{ inputs.IncludeFileToReplace }}' and Replace to '${{ inputs.ApiUrl }}'
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "#{BaseAddressUrl}"
          replace: ${{ inputs.ApiUrl }}
          include: ${{ inputs.RootPath }}/${{ inputs.IncludeFileToReplace }}
          regex: false

      - name: Find '#{APPENV}' in '${{ inputs.RootPath }}/wwwroot/manifest.webmanifest' and Replace to '${{ env.SufixAppName }}'
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "#{APPENV}"
          replace: ${{ env.SufixAppName }}
          include: ${{ inputs.RootPath }}/wwwroot/manifest.webmanifest
          regex: false
      
      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Obtendo o PUBLISH_TOKEN do StaticWebApp
        id: get-token
        run: |
          TOKEN=$(az staticwebapp secrets list --name $ResourceName --resource-group $ResourceGroup --query "properties.apiKey" -o tsv)     
          echo "PUBLISH_TOKEN=$TOKEN" >> $GITHUB_OUTPUT
        
      - name: Build And Deploy Blazor
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ steps.get-token.outputs.PUBLISH_TOKEN }}
          app_location: ${{ inputs.RootPath }}
          app_artifact_location: ${{ inputs.OutPath }}

