name: Azure Terraform IaC


on:
  workflow_call:
    inputs:
      Project:
        required: true
        type: string
        description: "Nome do Projeto que está sendo publicado"
      AppEnv:
        required: true
        type: string
        description: "Ambiente que será feito a publicação (DEV, HMG, STG, PRD, etc)"
      ConnectionStringType:
        required: false
        type: string
        default: "SQLServer"
        description: "Tipo de Banco de dados que a aplicação usará (Necessário para a criação da chave de connectionString no Azure)"
      ConnectionStringName:
        required: false
        type: string
        default: "Default"
        description: "Nome da Chave de ConnectionString (Necessário para a criação da chave de connectionString no Azure)"
    secrets:
      ConnectionStringValue:
        required: true
        description: "ConnectionString com o Banco de dados"
      AZURE_CREDENTIALS:
        required: true
        description: |
          Json contendo as credenciais do Azure. para obter essa credencial, rode no azure o comando abaixo:
          az ad sp create-for-rbac --name "github-actions" --role contributor --scopes /subscriptions/#subscriptionId#
          O Azure vai retornar um Json semelhante ao abaixo
          {
            "appId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeffffff",
            "displayName": "github-actions",
            "password": "#Password+Secreta*Gerada+Automaticamente!",
            "tenant": "ffffffff-eeee-dddd-cccc-bbbbbbaaaaaa"
          }
          Você precisa converter o Json retornado acima em algo conforme o json abaixo:
          {
            "clientId": "appId",
            "clientSecret": "password",
            "subscriptionId": "#subscriptionId#",
            "tenantId": "tenant"
          }


jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action v6
      uses: actions/checkout@v6
      with:
        submodules: true
        repository: Strategile/workflows
        path: ./

    - name: Login Azure
      uses: azure/login@v3
      with:
          auth-type: SERVICE_PRINCIPAL
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configurando o Terraform v4
      uses: hashicorp/setup-terraform@v4

    - name: Terraform Init Upgrade (${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform init -upgrade

    - name: Terraform Workspace (${{ inputs.Project }}-${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform workspace select -or-create $WORKSPACE
      env:
         WORKSPACE: "${{ inputs.Project }}-${{ inputs.AppEnv }}"

    - name: Terraform Validate (${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform validate

    - name: Terraform Plan (${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform plan -out main.tfplan
      env:
        TF_VAR_Project: ${{ inputs.Project }}
        TF_VAR_AppEnv: ${{ inputs.AppEnv }}
        TF_VAR_ConnectionStringType: ${{ inputs.ConnectionStringType }}
        TF_VAR_ConnectionStringName: ${{ inputs.ConnectionStringName }}
        TF_VAR_ConnectionStringValue: ${{ secrets.ConnectionStringValue }}

    - name: Terraform Apply (${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform apply -auto-approve -input=false main.tfplan


