name: Base Windows Console App

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      OUTPUT_PATH:
        required: true
        type: string
      CONFIGURATION:
        required: true
        type: string
      DOTNET_VERSION:
        required: true
        type: string
      FTP_PATH:
        required: true
        type: string
    secrets:
      FTP_PWD:
        required: true


jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: windows-latest
      
    steps:
      - name: Checkout GitHub Action v6
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup .NET Core ${{ inputs.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}

      - name: Build And Publish ${{ inputs.WORKING_DIRECTORY }} / ${{ inputs.CONFIGURATION }} in ${{ inputs.OUTPUT_PATH }}
        shell: powershell
        run: |
          dotnet publish "${{ inputs.WORKING_DIRECTORY }}" --configuration ${{ inputs.CONFIGURATION }} --output ${{ inputs.OUTPUT_PATH }}
          Del ${{ inputs.OUTPUT_PATH }}\appsettings.json

      - name: Creating Package upload\Strategile.SyncDataApp.zip
        shell: powershell
        run: |
          MkDir upload\
          MkDir output\Config\
          Copy src\SyncDataApp\Properties\Config\upload*.ps1     upload\
          Copy src\SyncDataApp\Properties\Config\Atualizar.bat   output\
          Copy src\SyncDataApp\Properties\Config\Executar.bat    output\
          Copy src\SyncDataApp\Properties\Config\RunSetup.bat    output\Config\
          Copy src\SyncDataApp\Properties\Config\RunUpdate.bat   output\Config\
          Copy src\SyncDataApp\Properties\Config\Strategile*.xml output\Config\
          Copy src\SyncDataApp\Properties\Config\template*.json  output\Config\

          Compress-Archive -Force -DestinationPath upload\Config.zip                 -Path output\Config\ , output\*.*
          Compress-Archive -Force -DestinationPath upload\Strategile.SyncDataApp.zip -Path ${{ inputs.OUTPUT_PATH }}
    
      - name: Deploy Release to FTP Server
        shell: powershell
        run: |
          . .\upload\upload-to-ftp.ps1
          Ftp-Deploy "${{ secrets.FTP_PWD }}" "${{ inputs.FTP_PATH }}" "Config.zip"
          Ftp-Deploy "${{ secrets.FTP_PWD }}" "${{ inputs.FTP_PATH }}" "Strategile.SyncDataApp.zip"

