name: Base Save GitHub Secrets

on:
  workflow_call:
    inputs:
      NAME1:
        type: string
        required: true
      NAME2:
        type: string
        required: true
      NAME3:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true
      VALUE1:
        required: true
      VALUE2:
        required: true
      VALUE3:
        required: true


jobs:
  github-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Save GitHub Secrets 
      run: |
        gh secret set ${{ inputs.NAME1 }} --repo ${{ github.repository }} --body {{ secrets.VALUE1 }}
        gh secret set ${{ inputs.NAME2 }} --repo ${{ github.repository }} --body {{ secrets.VALUE2 }}
        gh secret set ${{ inputs.NAME3 }} --repo ${{ github.repository }} --body {{ secrets.VALUE3 }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
