name: Base Azure Function Web Api


on:
  workflow_call:
    inputs:
      Project:
        required: true
        type: string
      AppEnv:
        required: true
        type: string
      RootPath:
        required: true
        type: string
      OutPath:
        required: true
        type: string
      DotNetVersion:
        required: false
        type: string
        default: '10.0.x'
      Configuration:
        required: false
        type: string
        default: "Release"
      FunctionSlot:
        required: false
        type: string
        default: "Production"
      FunctionSku:
        required: false
        type: string
        default: "flexconsumption"
    secrets:
      AZURE_CREDENTIALS:
        required: true


jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest

    env:
      RESOURCE_NAME: "${{ inputs.Project }}-${{ inputs.AppEnv }}"
    
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET Core ${{ inputs.DotNetVersion }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.DotNetVersion }}

      - name: Restore ${{ inputs.RootPath }}
        run: dotnet restore "${{ inputs.RootPath }}"

      - name: Build And Publish ${{ inputs.RootPath }} / ${{ inputs.Configuration }} in ${{ inputs.OutPath }}
        run: dotnet build "${{ inputs.RootPath }}" --Configuration ${{ inputs.Configuration }} --output ${{ inputs.OutPath }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Function App ${{ inputs.Project }} @ ${{ inputs.AppEnv }} from ${{ inputs.OutPath }}
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.RESOURCE_NAME }}
          slot-name: ${{ inputs.FunctionSlot }}
          package: ${{ inputs.OutPath }}
          sku: ${{ inputs.FunctionSku }}
