name: Base Windows Console App

on:
  workflow_call:
    inputs:
      Project:
        required: true
        type: string
      AppEnv:
        required: true
        type: string
      RootPath:
        required: true
        type: string
      OutPath:
        required: true
        type: string
      FtpPath:
        required: true
        type: string
      Configuration:
        required: false
        type: string
        default: Release
      DotNetVersion:
        required: false
        type: string
        default: "10.0.x"
    secrets:
      FTP_CREDENTIALS:
        required: true


jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: windows-latest
      
    steps:
      - name: Checkout GitHub Action v6
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup .NET Core ${{ inputs.DotNetVersion }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.DotNetVersion }}

      - name: Build And Publish ${{ inputs.RootPath }} / ${{ inputs.Configuration }} in ${{ inputs.OutPath }}
        shell: powershell
        run: |
          dotnet publish "${{ inputs.RootPath }}" --configuration ${{ inputs.Configuration }} --output ${{ inputs.OutPath }}
          Del ${{ inputs.OutPath }}\appsettings.json

      - name: Creating Package upload\${{ inputs.Project }}.SyncDataApp.zip
        shell: powershell
        run: |
          MkDir upload\
          MkDir output\Config\
          Copy src\SyncDataApp\Properties\Config\upload*.ps1     upload\
          Copy src\SyncDataApp\Properties\Config\Atualizar.bat   output\
          Copy src\SyncDataApp\Properties\Config\Executar.bat    output\
          Copy src\SyncDataApp\Properties\Config\RunSetup.bat    output\Config\
          Copy src\SyncDataApp\Properties\Config\RunUpdate.bat   output\Config\
          Copy src\SyncDataApp\Properties\Config\${{ inputs.Project }}*.xml output\Config\
          Copy src\SyncDataApp\Properties\Config\template*.json  output\Config\

          Compress-Archive -Force -DestinationPath upload\Config.zip                 -Path output\Config\ , output\*.*
          Compress-Archive -Force -DestinationPath upload\${{ inputs.Project }}.SyncDataApp.zip -Path ${{ inputs.OutPath }}
    
      - name: Deploy Release to FTP Server
        shell: powershell
        run: |
          . .\upload\upload-to-ftp.ps1
          Ftp-Deploy "${{ secrets.FTP_CREDENTIALS }}" "${{ inputs.FtpPath }}" "Config.zip"
          Ftp-Deploy "${{ secrets.FTP_CREDENTIALS }}" "${{ inputs.FtpPath }}" "${{ inputs.Project }}.SyncDataApp.zip"

