name: Base Azure Static Web App


on:
  workflow_call:
    inputs:
      PROJECT:
        required: true
        type: string
      APPENV:
        required: true
        type: string
      TYPE:
        required: true
        type: string
      APP_LOCATION:
        required: true
        type: string
      API_LOCATION:
        required: true
        type: string
      APP_ARTIFACT:
        required: true
        type: string
      IncludeFileToReplace:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy 

    env:
      RG_NAME: "RG-${{ inputs.PROJECT }}-${{ inputs.APPENV }}"
      RESOURCE_NAME: "${{ inputs.PROJECT }}-${{ inputs.APPENV }}-${{ inputs.TYPE }}"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Find '#{BaseAddressUrl}' in '${{ inputs.APP_LOCATION }}/${{ inputs.IncludeFileToReplace }}' and Replace to '${{ inputs.API_LOCATION }}'
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "#{BaseAddressUrl}"
          replace: ${{ inputs.API_LOCATION }}
          include: ${{ inputs.APP_LOCATION }}/${{ inputs.IncludeFileToReplace }}
          regex: false

      - name: Find '#{CACHE_VERSION}' in '${{ inputs.APP_LOCATION }}/wwwroot/*.*' and Replace to '${{ github.run_id }}'
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "#{CACHE_VERSION}"
          replace: ${{ github.run_id }}
          include: ${{ inputs.APP_LOCATION }}/wwwroot/*.*
          regex: false

      - name: Find '#{APPENV}' in '${{ inputs.APP_LOCATION }}/wwwroot/manifest.webmanifest' and Replace to '${{ inputs.APPENV }}'
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "#{APPENV}"
          replace: ${{ inputs.APPENV }}
          include: ${{ inputs.APP_LOCATION }}/wwwroot/manifest.webmanifest
          regex: false
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Obtendo o PUBLISH_TOKEN do StaticWebApp
        id: get-token
        run: |
          TOKEN=$(az staticwebapp secrets list --name $RESOURCE_NAME --resource-group $RG_NAME --query "properties.apiKey" -o tsv)     
          echo "PUBLISH_TOKEN=$TOKEN" >> $GITHUB_OUTPUT
        
      - name: Build And Deploy Blazor
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ steps.get-token.outputs.token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: ${{ inputs.APP_LOCATION }}
          app_artifact_location: ${{ inputs.APP_ARTIFACT }}
