name: Base Infra

on:
  workflow_call:
    inputs:
      PROJECT:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      GH_TOKEN:
        required: true


jobs:
  terraform:
    runs-on: ubuntu-latest
    #environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - name: Login Azure
      uses: azure/login@v2
      with:
          auth-type: SERVICE_PRINCIPAL
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

    - name: Checkout Terraform repo
      uses: actions/checkout@v4
      with:
        repository: Strategile/workflows
        path: ./

    - uses: hashicorp/setup-terraform@v4

    - name: Terraform Init Upgrade (${{ inputs.ENVIRONMENT }})
      working-directory: infra
      run: terraform init -upgrade

    - name: Terraform Workspace (${{ inputs.PROJECT }}-${{ inputs.ENVIRONMENT }})
      working-directory: infra
      run: |
        WORKSPACE="${{ inputs.PROJECT }}-${{ inputs.ENVIRONMENT }}"
        terraform workspace select -or-create $WORKSPACE

    - name: Terraform Validate (${{ inputs.ENVIRONMENT }})
      working-directory: infra
      run: terraform validate

    - name: Terraform Plan (${{ inputs.ENVIRONMENT }})
      working-directory: infra
      run: terraform plan -out main.tfplan -var="project=${{ inputs.PROJECT }}" --var="env=${{ inputs.ENVIRONMENT }}"

    - name: Terraform Apply (${{ inputs.ENVIRONMENT }})
      working-directory: infra
      run: terraform apply -auto-approve -input=false main.tfplan

    - name: Terraform Outputs (${{ inputs.ENVIRONMENT }})
      id: tfout
      working-directory: infra
      run: |
        V1=$(terraform output -raw landing_page_deployment_token)
        V2=$(terraform output -raw blazor_webapp_deployment_token)
        echo "SECRET_landing_page_deployment_token=$V1" >> $GITHUB_OUTPUT
        echo "SECRET_blazor_webapp_deployment_token=$V2" >> $GITHUB_OUTPUT
    
    - name: Save GitHub Secrets (${{ inputs.ENVIRONMENT }})
      run: |
        gh secret set ${{ inputs.ENVIRONMENT }}_LANDING_PAGE_DEPLOY_TOKEN  --repo ${{ github.repository }} --body $SECRET1
        gh secret set ${{ inputs.ENVIRONMENT }}_BLAZOR_WEBAPP_DEPLOY_TOKEN --repo ${{ github.repository }} --body $SECRET2
        gh secret set ${{ inputs.ENVIRONMENT }}_FUNCTION_API_DEPLOY_TOKEN  --repo ${{ github.repository }} --body "SECRET"
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SECRET1: ${{ steps.tfout.outputs.SECRET_landing_page_deployment_token }}
        SECRET2: ${{ steps.tfout.outputs.SECRET_blazor_webapp_deployment_token }}

  
