name: Base Infra

on:
  workflow_call:
    inputs:
      PROJECT:
        required: true
        type: string
      ENV:
        required: true
        type: string
      INFRA_CONNECTION_STRING_TYPE:
        required: true
        type: string
      INFRA_CONNECTION_STRING_NAME:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      INFRA_CONNECTION_STRING_VALUE:
        required: true
      GH_TOKEN:
        required: true


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Login Azure
      uses: azure/login@v2
      with:
          auth-type: SERVICE_PRINCIPAL
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

    - name: Checkout Terraform repo
      uses: actions/checkout@v4
      with:
        repository: Strategile/workflows
        path: ./

    - uses: hashicorp/setup-terraform@v4

    - name: Terraform Init Upgrade (${{ inputs.ENV }})
      working-directory: infra
      run: terraform init -upgrade

    - name: Terraform Workspace (${{ inputs.PROJECT }}-${{ inputs.ENV }})
      working-directory: infra
      run: terraform workspace select -or-create $WORKSPACE
      env:
         WORKSPACE: "${{ inputs.PROJECT }}-${{ inputs.ENV }}"

    - name: Terraform Validate (${{ inputs.ENV }})
      working-directory: infra
      run: terraform validate

    - name: Terraform Plan (${{ inputs.ENV }})
      working-directory: infra
      run: terraform plan -out main.tfplan
      env:
        TF_VAR_project: ${{ inputs.PROJECT }}
        TF_VAR_env: ${{ inputs.ENV }}
        TF_VAR_ConnectionStringType: ${{ inputs.INFRA_CONNECTION_STRING_TYPE }}
        TF_VAR_ConnectionStringName: ${{ inputs.INFRA_CONNECTION_STRING_NAME }}
        TF_VAR_ConnectionStringValue: ${{ secrets.INFRA_CONNECTION_STRING_VALUE }}

    - name: Terraform Apply (${{ inputs.ENV }})
      working-directory: infra
      run: terraform apply -auto-approve -input=false main.tfplan

    - name: Save GitHub Secrets (${{ inputs.ENV }}) from Terraform Outputs (${{ inputs.ENV }})
      working-directory: infra
      run: |
        SECRET_NAME1="${{ inputs.ENV }}_LANDING_PAGE_DEPLOY_TOKEN"
        SECRET_VALUE1=$(terraform output -raw landing_page_deployment_token)

        SECRET_NAME2="${{ inputs.ENV }}_BLAZOR_WEBAPP_DEPLOY_TOKEN"
        SECRET_VALUE2=$(terraform output -raw blazor_webapp_deployment_token)

        SECRET_NAME3="${{ inputs.ENV }}_FUNCTION_API_DEPLOY_TOKEN"
        SECRET_VALUE3="SecretPrecisaSerConfiguradoManualmenteParaConsumoFlex"

        gh secret set $SECRET_NAME1 --repo ${{ github.repository }} --body $SECRET_VALUE1
        gh secret set $SECRET_NAME2 --repo ${{ github.repository }} --body $SECRET_VALUE2

        if gh secret list --repo ${{ github.repository }} | awk '{print $1}' | grep -Fxq "$SECRET_NAME3"; then
          echo "Secret $SECRET_NAME3 já existe. Nada a fazer 👍"
        else
          echo "Criando secret $SECRET_NAME3..."
          gh secret set $SECRET_NAME3 --repo ${{ github.repository }} --body $SECRET_VALUE3
        fi
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}



  

