name: Base Infra

on:
  workflow_call:
    inputs:
      Project:
        required: true
        type: string
      AppEnv:
        required: true
        type: string
      ConnectionStringType:
        required: false
        type: string
        default: "SQLServer"
      ConnectionStringName:
        required: false
        type: string
        default: "Default"
    secrets:
      AZURE_CREDENTIALS:
        required: true
      ConnectionStringValue:
        required: true


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Login Azure
      uses: azure/login@v2
      with:
          auth-type: SERVICE_PRINCIPAL
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout Terraform repo
      uses: actions/checkout@v4
      with:
        repository: Strategile/workflows
        path: ./

    - uses: hashicorp/setup-terraform@v4

    - name: Terraform Init Upgrade (${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform init -upgrade

    - name: Terraform Workspace (${{ inputs.Project }}-${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform workspace select -or-create $WORKSPACE
      env:
         WORKSPACE: "${{ inputs.Project }}-${{ inputs.AppEnv }}"

    - name: Terraform Validate (${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform validate

    - name: Terraform Plan (${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform plan -out main.tfplan
      env:
        TF_VAR_Project: ${{ inputs.Project }}
        TF_VAR_AppEnv: ${{ inputs.AppEnv }}
        TF_VAR_ConnectionStringType: ${{ inputs.ConnectionStringType }}
        TF_VAR_ConnectionStringName: ${{ inputs.ConnectionStringName }}
        TF_VAR_ConnectionStringValue: ${{ secrets.ConnectionStringValue }}

    - name: Terraform Apply (${{ inputs.AppEnv }})
      working-directory: infra
      run: terraform apply -auto-approve -input=false main.tfplan


