name: Base Infra

on:
  workflow_call:
    inputs:
      PROJECT:
        required: true
        type: string
      APPENV:
        required: true
        type: string
      API_CONNECTION_STRING_TYPE:
        required: true
        type: string
      API_CONNECTION_STRING_NAME:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      API_CONNECTION_STRING_VALUE:
        required: true
      GH_TOKEN:
        required: true


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Login Azure
      uses: azure/login@v2
      with:
          auth-type: SERVICE_PRINCIPAL
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout Terraform repo
      uses: actions/checkout@v4
      with:
        repository: Strategile/workflows
        path: ./

    - uses: hashicorp/setup-terraform@v4

    - name: Terraform Init Upgrade (${{ inputs.APPENV }})
      working-directory: infra
      run: terraform init -upgrade

    - name: Terraform Workspace (${{ inputs.PROJECT }}-${{ inputs.APPENV }})
      working-directory: infra
      run: terraform workspace select -or-create $WORKSPACE
      env:
         WORKSPACE: "${{ inputs.PROJECT }}-${{ inputs.APPENV }}"

    - name: Terraform Validate (${{ inputs.APPENV }})
      working-directory: infra
      run: terraform validate

    - name: Terraform Plan (${{ inputs.APPENV }})
      working-directory: infra
      run: terraform plan -out main.tfplan
      env:
        TF_VAR_project: ${{ inputs.PROJECT }}
        TF_VAR_env: ${{ inputs.APPENV }}
        TF_VAR_ConnectionStringType: ${{ inputs.API_CONNECTION_STRING_TYPE }}
        TF_VAR_ConnectionStringName: ${{ inputs.API_CONNECTION_STRING_NAME }}
        TF_VAR_ConnectionStringValue: ${{ secrets.API_CONNECTION_STRING_VALUE }}

    - name: Terraform Apply (${{ inputs.APPENV }})
      working-directory: infra
      run: terraform apply -auto-approve -input=false main.tfplan

    - name: Save GitHub Secrets (${{ inputs.APPENV }}) from Terraform Outputs (${{ inputs.APPENV }})
      working-directory: infra
      run: |
        SECRET_NAME1="${{ inputs.APPENV }}_LANDING_PAGE_DEPLOY_TOKEN"
        SECRET_VALUE1=$(terraform output -raw landing_page_deployment_token)

        SECRET_NAME2="${{ inputs.APPENV }}_BLAZOR_WEBAPP_DEPLOY_TOKEN"
        SECRET_VALUE2=$(terraform output -raw blazor_webapp_deployment_token)

        gh secret set $SECRET_NAME1 --repo ${{ github.repository }} --body $SECRET_VALUE1
        gh secret set $SECRET_NAME2 --repo ${{ github.repository }} --body $SECRET_VALUE2
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}



  

