name: Windows Console App


on:
  workflow_call:
    inputs:
      Project:
        required: true
        type: string
        description: "Nome do Projeto que está sendo publicado"
      AppEnv:
        required: true
        type: string
        description: "Ambiente que será feito a publicação (DEV, HMG, STG, PRD, etc)"
      RootPath:
        required: true
        type: string
        description: "Pasta Raiz do Projeto Console (o caminho pode ser um path relativo do repositório, i.e., src/ConsoleApp/)"
      OutPath:
        required: true
        type: string
        description: "Pasta de saída (local onde os binários são gerados. Pode ser um caminho relativo)"
      FtpPath:
        required: true
        type: string
        description: "Path onde os Arquivos publicados serão disponibilizados no SFTP"
      DotNetVersion:
        required: false
        type: string
        default: "10.0.x"
        description: "Versão do .net para fazer o build ('8.0.x' ou '10.0.x')"
      Configuration:
        required: false
        type: string
        default: "Release"
        description: "Configuração do build ('Debug' ou 'Release')"
    secrets:
      FTP_CREDENTIALS:
        required: true
        description: |
          Json contendo as credenciais do Azure. para obter essa credencial, rode no azure o comando abaixo:
          az ad sp create-for-rbac --name "github-actions" --role contributor --scopes /subscriptions/#subscriptionId#
          O Azure vai retornar um Json semelhante ao abaixo
          {
            "appId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeffffff",
            "displayName": "github-actions",
            "password": "#Password+Secreta*Gerada+Automaticamente!",
            "tenant": "ffffffff-eeee-dddd-cccc-bbbbbbaaaaaa"
          }
          Você precisa converter o Json retornado acima em algo conforme o json abaixo:
          {
            "clientId": "appId",
            "clientSecret": "password",
            "subscriptionId": "#subscriptionId#",
            "tenantId": "tenant"
          }


jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout GitHub Action v6
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup .NET Core ${{ inputs.DotNetVersion }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.DotNetVersion }}

      - name: Build And Publish ${{ inputs.RootPath }} / ${{ inputs.Configuration }} in ${{ inputs.OutPath }}
        shell: powershell
        run: |
          dotnet publish "${{ inputs.RootPath }}" --configuration ${{ inputs.Configuration }} --output ${{ inputs.OutPath }}
          Del ${{ inputs.OutPath }}\appsettings.json

      - name: Creating Package upload\${{ inputs.Project }}.SyncDataApp.zip
        shell: powershell
        run: |
          MkDir upload\
          MkDir output\Config\
          Copy src\SyncDataApp\Properties\Config\upload*.ps1     upload\
          Copy src\SyncDataApp\Properties\Config\Atualizar.bat   output\
          Copy src\SyncDataApp\Properties\Config\Executar.bat    output\
          Copy src\SyncDataApp\Properties\Config\RunSetup.bat    output\Config\
          Copy src\SyncDataApp\Properties\Config\RunUpdate.bat   output\Config\
          Copy src\SyncDataApp\Properties\Config\${{ inputs.Project }}*.xml output\Config\
          Copy src\SyncDataApp\Properties\Config\template*.json  output\Config\

          Compress-Archive -Force -DestinationPath upload\Config.zip                 -Path output\Config\ , output\*.*
          Compress-Archive -Force -DestinationPath upload\${{ inputs.Project }}.SyncDataApp.zip -Path ${{ inputs.OutPath }}
    
      - name: Deploy Release to FTP Server
        shell: powershell
        run: |
          . .\upload\upload-to-ftp.ps1
          Ftp-Deploy "${{ secrets.FTP_CREDENTIALS }}" "${{ inputs.FtpPath }}" "Config.zip"
          Ftp-Deploy "${{ secrets.FTP_CREDENTIALS }}" "${{ inputs.FtpPath }}" "${{ inputs.Project }}.SyncDataApp.zip"

